services:
  jekyll:
    build: .
    container_name: praharsha-jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site
      - bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    stdin_open: true
    tty: true

volumes:
  bundle:
